package leetcode.problems.medium;

import java.util.HashMap;
import java.util.Map;

/**
 * 
 * https://leetcode.com/problems/longest-ideal-subsequence/description/
 * 
 * @author gaochf
 *
 */
public class LongestIdealSubsequence {

	public int longestIdealString(String s, int k) {
		int result = 0;
		// Map<index, lis ends at index>
		Map<Integer, Integer> lis = new HashMap<Integer, Integer>();
		for (int index = 0; index < s.length(); index++) {
			Map<Integer, Integer> tempLis = new HashMap<Integer, Integer>();
			int indexMax = 1;
			for (int key : lis.keySet()) {
				int diff = s.charAt(index) - s.charAt(key);
				diff = diff > 0 ? diff : -1 * diff;
				if (diff <= k) {
					int tempMax = lis.get(key) + 1;
					indexMax = tempMax >= indexMax ? tempMax : indexMax;
				}
				if(diff != 0) {
					tempLis.put(key, lis.get(key));
				}
			}
			tempLis.put(index, indexMax);
			lis.clear();
			lis.putAll(tempLis);
		}

		for (int value : lis.values()) {
			result = value > result ? value : result;
		}

		return result;
	}

	public static void main(String[] args) {
		LongestIdealSubsequence lis = new LongestIdealSubsequence();
		String param1 = "acfgbd";
		int param2 = 2;
		System.out.println("lis: " + lis.longestIdealString(param1, param2));

		param1 = "abcd";
		param2 = 3;
		System.out.println("lis: " + lis.longestIdealString(param1, param2));

		param1 = "jxhwaysa";
		param2 = 14;
		System.out.println("lis: " + lis.longestIdealString(param1, param2));

		param1 = "eduktdb";
		param2 = 15;
		System.out.println("lis: " + lis.longestIdealString(param1, param2));

		param1 = "fqyokqgzvjpermqmwcjqtzbxnurjmawsswlwzmnjbbhdtfjxnktwtonpeorewc";
		param2 = 3;
		System.out.println("lis: " + lis.longestIdealString(param1, param2));

		param1 = "mymqqhdyknqqtaiefwthqnpkipzjknqhmelmdoxxxozemfyyqyzlkosepmyvacbzqjzkpultyfazpumdsscqtenuagyrtagfjkjkrairafqlsolzlwwkcyblruwxstmyeyrjkgukwirewnonknjjwskhkoohwlbsaewyjaegnfouuksycrxsibjfqbhmhedcthnbiepywatalhlittczssztjcvjvsmxbvppdxpdlppkgimsfiemzsuocawhkqlsmedyxwaivebsneqapjmhienddnkiitbobangijfsdmbywqxjyjykumsdyolqgvcemvrdfzuicqfheyzixlqhpkucnkbunirlcdipekzgriwndplvdypmwzuasjkwairtzcneepvmuqgcqqdqpmbvmnprdepmgrzzvqgvoowhvbnqpohuifwkmtciledsutwhatcnbzyxemxhqontnkinzziqwkbqurysomviaunriilsjehvlfofhawtqxvixeqctanratlpsrooptdxvjcvpbmefetbzkapaextimcsernnizzesdwneqhwenhsqapbebxuicahoxfxxvhcnrmhlythajyhdcyeinwlkpvwjowuehtcfpmywnlceulsqqjblaglyznmzrvfzlsgkjyvyfsioweeoilxejiselbhrlupfaevbimgarksevcgjcrurtqgsvsmaumlzpulbbtvuqyvggyqemfwyazyasphvgdlbmvdlkhcbgbftevywgrtuyyrjmqoguusmwhpsocafisctosfhqlvbbdvwiipeqyprzfpfflrblhenesjlrlfueyexgmwmcadfnqwhabuesjhvfaciqdppguliwmbvothxyxffvcmjtkkvaalhlnpwsaawmfhgrmjlumhoxpqpsetiwtyzxiypvymsvscsudtjrkwpeavsfcgtrrxyombdxmtfjkfkibpoykcfhwzhcevepcoytdfoqdryyblzeeoupckccovjhryylgypkkolkcahigwuvpktlwoqjmouxgggieksgqagajxlzpcobjaoztxjmnxnwvfnjmykuimrzpuxucfcjnrgxapuyapueghxqsgcsfdepmnrwtjuwgggyzxcwpnvdbwvrtntldpqtqqgjwthtqmgmppbzcuhfsatounawolifqdtyszekcghqnyznihaqhdixnntlybmjefegmetnskeuflhfifuemejiufijcfgcjaksjmgfzrlsceawrhbaynqiyrcdomqiuelshkazdesrfuttqayfigdatzepudmymrnsyrgkhicpjgdprgqutqzwgghsssgnejvzrfecbnvojamzqosracuzqwmjtovkyqurckfgifcjohpljklqfjbzqoriyzaiywznxcnlfjldinkdrcyoglfdakklvmvozcgtjgokhkayyxkruwhplhflbgbhgvuoiakxettrzvgjxwxkhqfhspjmtyrvjsjxllseiakoryuuzgxcjrzofkwrtdcvsukzmwijuvxtgeivnfvqicbgzcwycvselqqnsciqkxvlhqtnyufjchxsknrtsfpazxohiumvgraemhajoocpdtxwlpijgrykivfcxpqzkquhegspjeclpuchxqktgosokrycrfuzuvzplkgthntvcmphiwwgvtqechedwyqpvoecocvudhsuasgqjjgxzilsjiighozpvlwopbiatfzshmzbgwmmvwzsqebtfpjvmvmddhpmftyunwwuplxodqhmklgmllvcgpiuactzbatmnmknhjbsooigcujrsrjttimmlksgbldrlfrghgiyocbtnpofvdmwvizgckambvolsucdgcvdroprtzboeahmxllmxkwspisrhtstuhgtaxrjzyrlzrhsiulzwjftnzupguufcgqptsyklllgtobxfwyajxcdpwaoeqonqnmqlubjvwnxhaiiilnvncpvfxfkwipapmcuiezqaybygjmvitywrlhsgnemtzntvsbzydonegbqnvpuajnxqplknobtnekcjmfdpeupwffmjgyajnkmxsnacigyomjpkthmithabqsuhufmlfvuyzchlnasaxaospgbzxpbpahnqknfefmywnfbnhscihmjepiwekuqkymwgxfanyhkdamybkpmlbwkgnxrntvemspzqpgbqjfkmgfdvdgvpywrmmsrfnzqalkssvsveudzipgizkeisuxayqaqlgzgkixmiykeomvusneckfoxbubpbninnugqaashlzapmydeysbgobpjkqenuleqrerovclwdyljvzuhcpaiuzrgnvdvukrtauzgkjspkwfcwvuenudysydvhptqmberormkgfatvmscatafwvwjvmyvztqncuxisbekjuyrmaymkqameyzhkkwfdzwrltsudrzmylrigecrkoehdrixgiqejgmomeuexfnrjnrgtogmxqimnnxuqhinmiayacqtokuekpclfvtnludopglqduviwjvmzkxpkghtdvigxqmfmqnedogiuhdnrxphskhrxmwnklshisgccpdqoykjzjcpqafgzvwzfpwgvlvrsbisopfwzmbnevxdhqaotqzsemyuwmkgvfqsafbyefwieqzfkbljytuucufvdjbiulxmxqzseunsesxgpegimefvxkmnsqctmmzxocvgbmpsbzeiuqnojvcnrtscgnoibdawjgmlqroeckxmpartkqdlbqfiyukovuoprhsrzyjwkcoknnkinwcjogmclttqwhfqrgrnbymrahgzdmikpbqgtniwrourtchgmijxnsjrqbvgrpxichmwfidbmpwxstuukcldveqttjjrdqwqnhiuhomgovcfbxaqsvqyyscpgxjaihexwhflnluxxttikurcrbznagzzuiwstommflwidgfusszkzlpbnxrkhthclefwcpjjifxslgsyamjumgovdncxjnbzqowxctbkqfciqmgtgxprrjrbnyxlmtaqoiozxtzldcwlzulknfvryzhblcbmgentzgrjaobwrpsysfikvvzjbahkopxmcgadihbbdfktekqlnaoogedofvgaouzdpwlxhaenrdwccnnwwetzcjxhqwwjidotnycitjshdocahdxcxgqpgyqzegjzpzdgylbznubfgsvjgvxgovtnfuuiowvzrbgggfpikleqifckhoieadtuuewsedkeguuyzjdhgywoykfbfnktimgofuyvqblwuaixnjyiymuuudjxxonoayxmyqzaheslxpbpqhgpoaibkkaucmdevvgndbkebxqajzjtgbmgeqwfydnfferriaysmivovrjehhpkwsfawogeoxxykhzarrqdimgdzvegvbksrvuvbwafumnzoypicaaecqhnwmzutmwagagxgqdcywnpdyzcgurmjhqevdnnphybotacpipdganlyumttddydwgksfxuxyjgejkkthitkfiglkzyknpjhrrzvvxgpawnltwyyjsobgsqgiepygsvfxsifnmrphtwklxcbfeghepoxzxxtihnkdwlzqwtvegocgygnqbvighsklipncymwsnbqyxrqzzglkgnylwaxkcpwdwsjcqcuhrphybupkiriewglexfyydoirgfqiafqonbcmopqqcyoivqxlkuxslfayuznqsjulmixafifjhcoxhfpltozteddxqswrntunycrnieczpvzdxrdethyomapechuxqmvhgcqqmrdzmdogrwyeujyhdmmioetiwiybgrqtsvknksvidmkdtdosstcdozbheubpfnoqrjmtobvnpflcpkecyoahifqexpzjqrwtmasesqsiuvgypyntpotbuwxwxapimshjyypmeksovwpmzkshlfyfiwohcwpyqkpkygbmvxldttmqqcohxfnpyexqqtcbnfsmkagehoattngxvjhxmlwpgkjxjwiszxbmfailiigkwxhprwmihrqzrblgfkintswktqdmcnbxikbowzoldrdkmnefphdmhrrpaqlaqhiognhooprbmmpzowgejmgcelkwxgfsawubmepayaqgrrynnemaiaxhzsecqkgehuasltkqnqhhanujfvvxsebllwwjagzfvngetiyvvcnjiycehrenfmrkylkdswidlmoapxfddwumyucuhiwebanbnikfbgiwumegcknvimjmyfzebtnwvzzgtwlbwtgvoaynhtvvpwspqaqxlyodyajkyuwwwqvdipjduowlwiarkjneorvahtafhugvujpmwrygzndagmdotiypofvnaiotraljmktqskhfullszowzlntudsqvpkfigqjohensyrboqokakerqsiymjlgtpmjoaczixmtddnineyncwnqggmnimtcyhzrfftyvommnjlnhshpawwbsvjpjcisrjmramikeqmmgibpbzkrjfasengkntpiqcluefpunjvwsqsapbyojicpuhmgbhyvuqogxwndmirtwzxnfvfczsrxefcmbkhkvofjpptpixzvvsumurarjiaxsjbsidrzwhluistirkergvvnzxqfsufkhrkenjckhmmglspzlqplbllpxsuvbrbmctfbxicbtzhiulssuoosmhuehuhlhcsjdpxpvdkdrlnkvjwvozhzkftekozmjejnbkyzpwyltzxanfqksxcfuzpqtwuwavmqecvpakdmwzbtidngnyxvvrsuulpenpmbvxkaxmswkyemsefnduscomifautmwpfnpidxeoatmoneybjxefvrmboibltkrveciloixzcxnbrclndnihlkdcausarknehmuspyozxdjvfcjnnhhlguxdkiqragncrdkinkzrhytjefcwapdmqspikfratxgkuxhlvweefkohunwfzdwbhcyujshydknbnrswoopkcdbmareuwlqojxsixnjuhdmsuqrpsxlniorfinmwwguorettbjwuyeemksjjzdroxicpcizaofhvqeqbwvlbgjhzkfzimvcgxyonwnixwfjhheooobrpjsteemxfuewgnxpdcotbkeriuzaxbwqidsgplmcmxdqpiqnkaujdmedwpnqmzhoedmmqplxstgsyiurpkotrfgndtqjyvjzondrtmlewrxvtjcpmaqtnsliibznrrngojbernfpnemdooduiyvnuczyqquqdthfffgpatbofqkfzvjcnvmximonkmdhxtgdzhevsknuqghvqznpgqoxgggwlazsjdklwdivooessifvhciecxoyjfcsjjngpjjpiojjlswbvztywyixrkxpkhadjxchlqbxxvediyoaxfdcjnpyohsfbflyjxmztymkwkokhbnjzamrvdgccfdlwxzzjztocsmvbjncnuvmusubbyjsnpkbglyydetcwrpbhejmfroikkbdkwjjiknstolbefkhpmusjturrolxqkyrpueuvtkrrlijwtkacjekiuqfjbkljsjxwzdyjvaafwgpxenbgupkanukljcxgqatuoxilsuqfrifjsrfidshhidetmfpopyrhzynuyuyhakzufgkazeiqvrohbjhywqxwdjzdiwwkqywclwuceizpkfzjkiffxvvfvivvhubdikumpdbjfotfpbhdfjohtqubkbahoytavdvmdebqzpuetksqhfcdydqcpmqrojglggumuffvyndocrgvkqixztyqxctwwuzmvvexzxfkxxnpdghoplmrvjhgardmsevqjvdbjlxopqtqzbeagdflmjfkrdndwjsskqfbiyftkscogocmiuumkzqnqiogqbwxebedivxcyqgwmhyzucjdevkgdewmiqcdotlaatyxskzeyxzxirypdndzhrjjlbvstvsvfygsoqtcmllnmifmzlhztcqkwmihmmghpaaedecxqadeucinbzsyeqccfttwpcvuafztouxjhwmhzxnadnsniwktzzbekztpnirnntkdeyiqryxkcfwbkyfbjjgjdrodehgqwpgnwbqmvizdxqcocjvhmuiaxczerxgyucdqmlvlacynucvmjkszxrkeoowaqzdrdcvioeqcykuwzsoeraochpomyvgisxvzcytddlkchookofsgtgigvukiphssauvpdkodgqsyoiqzbqjidypgnkukungkhzfzqmplyruxyamjauaqnpxnpjiwrxjsaoosywargyklgvpxbjzhwmopgxuuifniwidoeomqzmmtskhheomzooirazvxiwzkyplntzssowqhdceblmncytfmxdusskuhftlbrwuhdtzseatlffiwsqbgytnyngisiznwowjonpeegibxtleivhvsuxwuxmjnftkwvtlffktszvdfxmgxtkfkbkswavimojatocfytamaexuccxmlmiygbfsqzqqwkymlpmtctjhnmfqtpuecjoqbymdsnlrjgdfhaagpztvlylqhqcmxssednizromzizmkhksppcuxkabaimsbcmyyrjygbhggawighrxeonueefvpswgkgvphrqbelnhavjqrxjgazvbfzzjtftedjefsvfpxqsmfbzryknhxfbkxtqpkqdrwyxnhpzwgyyxxjrfjrzfgmmrgljxnfllvyasacvrtpedewzuryxwecefxqwiebswbzfyrnyqeyjrzozpfhlsqzneuxzbbtjuwlflqasthrphcegeafjvtlcyokadqvayhmxsirhzdbojlrvbjtdexpmledbpifuyarqebzutocomtvidmtxeghbczoegnehazbslavqvwzuluzyimojdlbnrtvrsbycijfrubcvhmhmblumfsmxeatiynzhrdhuypuzuwcukyhvpwesolpkvsfxmocufsezfllqikszgdmdsbljminbdskiumymgvnvvvokcmkrpwiphahyjctggfjfbuezejecbqbahwzljelhzxdfdwcmdxipgfczsejxydyewtjrfmyijsqpxayfgbbqfdbjblfdtsraemvehwtkqcekhcsarhtrgicaithtmitnwppbvvtmhihconesvwvmgraecmskglkjptkjzwhcfddijmnshanyvlftperzfxpgccemschpdbemytimjjqlumfqhdbdyykpgeplhwzzokfajaqaeyjfvqgbpaokynqzhgvxckvkxjyfyqrzpijubikprvjozzfvvavlvqhcwevhssjvjgipokegopyfrfffspakxquwtauewztfjrssdmezsaofpwcivroxufzumqarxenowlbwptniayyjnmvchfnqjaeoipskqisoewtzdzoohertdxpfygpgvebqrevbigkbdmdcqrscyrvibgionhodfrhytfvxtrafvtqopatvmtasctxbwmjvhwglvj";
		param2 = 10;
		System.out.println("lis: " + lis.longestIdealString(param1, param2));

	}

}
